rtabmap:
  ros__parameters:
    frame_id: base_link
    odom_frame_id: odom
    subscribe_rgbd: true
    subscribe_scan: true
    use_action_for_goal: true
    map_always_update: true
    qos_scan: 2
    qos_image: 2
    approx_sync: true
    approx_sync_max_interval: 0.5
    topic_queue_size: 100
    sync_queue_size: 100
    Reg/Strategy: '1'
    Reg/Force3DoF: 'true'
    RGBD/NeighborLinkRefining: 'true'
    Grid/RangeMin: '0.2'
    Optimizer/GravitySigma: '0'
    Mem/STMSize: '30'
    Mem/ImageKept: 'false'
    Mem/BinDataKept: 'false'
    Rtabmap/TimeThr: '700'
    Kp/MaxFeatures: '200'
    Vis/MaxFeatures: '200'
    Grid/3D: 'false'
    RGBD/LinearUpdate: '0.1'
    RGBD/AngularUpdate: '0.1'

    subscribe_imu: "false"
    wait_imu_to_init: "false"
    imu_filter_madgwick/use_mag: 'false'
